# Copyright (C) 2022 Dynamic Solutions
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build checks

on:
  pull_request:

  schedule:
    - cron:  '30 3 * * 2,4'
    - cron:  '30 3 * * 1,3,5'

env:
  AWS_REGION: "eu-central-1"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_CI_ROLE_TO_ASSUME }}
          role-session-name: HowlitePullRequestCheck
          aws-region: ${{ env.AWS_REGION }}
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare Maven settings for Code Artifact
        run: |
              export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain websight --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --query authorizationToken --output text`
              mkdir -p ~/.m2/repository
              curl -s https://ws-dev-public.s3.eu-central-1.amazonaws.com/settings-code-artifact-deploy.xml --output ~/.m2/settings.xml
              echo "CODEARTIFACT_AUTH_TOKEN=${CODEARTIFACT_AUTH_TOKEN}" >> $GITHUB_ENV
      - name: Update snapshot version
        if: ${{ github.event_name == 'schedule' }}
        run: mvn -f tests/end-to-end/pom.xml versions:update-properties
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      - name: Build and test with Maven and Cypress
        if: >-
          github.event.name == 'pull_request' ||
          github.event.schedule != '30 3 * * 1,3,5'
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: mvn --batch-mode --update-snapshots clean verify -P e2e
      - name: Build and test visual with Maven and Percy
        if: github.event.schedule == '30 3 * * 1,3,5'
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          HOWLITE_PERCY_TOKEN: ${{ secrets.HOWLITE_PERCY_TOKEN }}
        run: mvn --batch-mode --update-snapshots clean verify -P e2e-visual
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
