# Copyright (C) 2023 Dynamic Solutions
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Create JIRA release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        type: string
        required: false
  workflow_call:
    inputs:
      tag:
        description: "Tag"
        type: string
        required: false

jobs:
  create-jira-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: '0'
      - name: Prepare release
        run: |
          PROJECT_NAME="WOS"
          RELEASE_NAME_PREFIX="howlite-"
          
          if [ -z "${{ inputs.tag }}" ]; then
            RELEASED_VERSION=$(git describe --tags --abbrev=0)
          else
            RELEASED_VERSION=${{ inputs.tag }}
          fi  
          
          echo "Released version: ${RELEASED_VERSION}"
          
          PREVIOUS_VERSION=$(git describe --abbrev=0 ${RELEASED_VERSION}^)
          echo "Previous version: ${PREVIOUS_VERSION}"
          
          COMMITS=$(git log ${PREVIOUS_VERSION}..${RELEASED_VERSION} --pretty=format:"%s" | grep ${PROJECT_NAME})
          echo "Commits with tickets: ${COMMITS}"
          if [ ! -z "${COMMITS}"]; then 
            TICKETS=$(echo "${COMMITS}" | grep -o ${PROJECT_NAME}'\-[0-9]\+' | sort -u | paste -sd "," -)
            echo "Tickets found in commit messages: ${TICKETS}"
          fi
          
          if [ ! -z "${TICKETS}" ]; then
            echo "HAS_TICKETS=true" >> $GITHUB_ENV
            echo "RELEASE_NAME=${RELEASE_NAME_PREFIX}${RELEASED_VERSION}" >> $GITHUB_ENV
            echo "TICKETS=${TICKETS}" >> $GITHUB_ENV
          else
            echo "HAS_TICKETS=false" >> $GITHUB_ENV
            echo "No tickets found. JIRA release won't be created."
          fi

      - name: Create release
        if: ${{ env.HAS_TICKETS == 'true' }}
        uses: armona/jira-release-actions@v2.0.6
        with:
          create: true
          email: ${{ secrets.ATLASSIAN_CLOUD_USER }}
          api_token: ${{ secrets.ATLASSIAN_CLOUD_APIKEY }}
          subdomain: ${{ secrets.ATLASSIAN_CLOUD_DOMAIN }}
          jira_project: 10201
          tickets: ${{ env.TICKETS }}
          release_name: ${{ env.RELEASE_NAME }}