# Copyright (C) 2022 Dynamic Solutions
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Howlite CI development version

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 3 * * 2,4'   # Cypress
    - cron:  '30 3 * * 1,3,5' # Percy

env:
  AWS_REGION: "eu-central-1"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test-latest-websight:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WEBSIGHT_RELEASES_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_WEBSIGHT_SNAPSHOTS_SNAPSHOT_READ_SA }}

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Update snapshot version
        run: ./mvnw --batch-mode -f tests/end-to-end/pom.xml versions:update-properties

      - name: Build and test with Maven and Cypress
        if: github.event_name == 'workflow_dispatch' || github.event.schedule == '30 3 * * 2,4'
        run: ./mvnw --batch-mode --update-snapshots clean verify -P e2e

      - name: Build and test visual with Maven and Percy
        if: github.event_name == 'workflow_dispatch' || github.event.schedule == '30 3 * * 1,3,5'
        env:
          HOWLITE_PERCY_TOKEN: ${{ secrets.HOWLITE_PERCY_TOKEN }}
        run: ./mvnw --batch-mode --update-snapshots clean verify -P e2e-visual